server.port: 9992

spring:
  application:
    name: bitcoin-scan
  codec:
    max-in-memory-size: 10MB
  main:
    allow-bean-definition-overriding: false
  cloud:
    bootstrap:
      enabled: true
    consul:
      port: 8500
      discovery:
        #healthCheckPath: ${management.context-path}/health
        instance-id: ${spring.application.name}:${server.port}
        healthCheckInterval: 20s
        prefer-ip-address: true

app:
  blockchain:
    rpc-url: https://btc.getblock.io/mainnet
    rest-url: https://btc.getblock.io/rest
    api-key: e0c0e8cd-d492-44f4-8309-11d6c41e77ae