server.port: 9991

spring:
  application:
    name: eth-scan
  main:
    allow-bean-definition-overriding: false
  cloud:
    bootstrap:
      enabled: true
    consul:
      port: 8500
      discovery:
        #healthCheckPath: ${management.context-path}/health
        instance-id: ${spring.application.name}:${server.port}
        healthCheckInterval: 20s
        prefer-ip-address: true
logging:
  level:
    co.nilin: DEBUG
    reactor.netty.http.client: DEBUG

blockchain:
  url: https://ropsten.infura.io/v3/fee0915a99f84c3c9971c253a9a9f6a2

swagger.authUrl: https://api.opex.dev
